### ISSUE TITLE
v1.26.1 tag doesn't exist in repo

### ISSUE THREAD

**Issue by dstaley** [Kinto/kinto-admin#1465]
The commit that the tag v1.26.1 points to doesn't exist in the repo.

https://github.com/Kinto/kinto-admin/commit/0d907414b067cda21428fe7a4866ddd5c84cf919

I think the tag was created from a detatched branch or something. When we release the next version we should make sure that we tie it to a commit in the repo just so things don't get lost.

@leplatrem since you made the release, would you mind double checking to ensure that the commits you made for the v1.26.0 and v1.26.1 tags exist in the main repo history? I did a spot check and it looks like they are, but I'd love a double-check on that if you get a chance!

**Comment by leplatrem** [comment]
I just pushed it when got `Everything up-to-date`, so I assume it was there already. It's listed here at least https://github.com/Kinto/kinto-admin/releases

I don't remember TBH, but I may have had to republish it without code change, because the package content was wrong (most likely the `lib/` folder). So, just bumped the version in `package.json`, rebuilt, and published.

**Comment by leplatrem** [comment]
Oh! I see!

The tag exists. But the branch does not.

I indeed pushed the tag, but not the commit :(

**Comment by leplatrem** [comment]
I published v1.26.2 with current master.
