### ISSUE TITLE
Unable to resubmit a collection JSON schema when entered JSON is invalid

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#236]
Reproduction steps:
1. Try to create a new collection
2. Enter invalid JSON in the schema editor, submit -> expected validation error
3. Fix the entered JSON, resubmit
4. Error stays and the form can never be submitted

Note: might be related to https://github.com/mozilla-services/react-jsonschema-form/issues/315

**Comment by diegocasmo** [comment]
I have a similar issue, though I'm able to re-submit the form (but validation errors won't disappear). This error only happens when I pass a custom method to the ``onSubmit`` prop. I took a look to the source code and it seems like the error could be happening here:

``` javascript
// Form.js
      if (_this.props.onSubmit) {
        _this.props.onSubmit(_this.state);
      }
      _this.setState({ status: "initial", errors: [], errorSchema: {} });
```
It behaves like if the ``setState`` method wasn't being called at all.

**Comment by Natim** [comment]
Should be fixed.
