### ISSUE TITLE
Error in permission checking when trying to update an existing records while in a group.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-admin#311]
I am in a group with a write permission on the bucket but cannot update the records there,

**Comment by leplatrem** [comment]
Workaround: disable endpoint permission on server

**Comment by n1k0** [comment]
So for clarification, is this a bug in kinto-admin code or a bug in the permission endpoint?

**Comment by leplatrem** [comment]
The bug was introduced in #296 which removed every smart stuff regarding permissions checking. kinto-admin now entirely relies on the permissions endpoint response *(if enabled on the server, else always return show edition buttons)*.

The problem here is that the permission endpoint does not *expand* the permissions on the sub-objects. For example, it would return that permissions on bucket `X` are `["read"]`, but would not return that permissions on collection `X/Y` is thus also `["read"]` as well, and on record `X/Y/abc`, etc...

There are two ways to fix it:
- Expand subobjects in the response of the permissions endpoint
- Reintroduce basic ascending permission checking in kinto-admin

The former would mean that the permission endpoint would return huge responses! Imagine you have the `write` permission on a bucket that has hundreds of collections with thousands of records! 

The latter would mean that we duplicate a bit of the permissions logics in the client. But it would still be a lot simpler than we had before #296, since we would not have the part that deduces `read` and `create` from `write` etc.

I propose that we add a new method in `kinto-http.js` that does the permission check. This way we have an official implementation, and we can keep the kinto-admin as dumb as possible for that part.

**Comment by n1k0** [comment]
Thanks for the explanation.

> I propose that we add a new method in kinto-http.js that does the permission check. This way we have an official implementation, and we can keep the kinto-admin as dumb as possible for that part.

Yeah sounds good :+1:

**Comment by leplatrem** [comment]
Fixed by #312
