### ISSUE TITLE
Order permissions before diff?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#407]
We should not show a diff for ther principals who weren't changed:

![screenshot from 2017-03-15 17-09-48](https://cloud.githubusercontent.com/assets/546692/23958379/376248d4-09a2-11e7-980e-3b8c8243bedd.png)

I'm not sure that the server guarantees the order of principals in the permissions. Maybe it should (*please open issue*).

In the meantime we could order them alphabetically...

**Comment by n1k0** [comment]
That would be a nice enhancement indeed, but I wouldn't qualify this as a *bug*.

**Comment by n1k0** [comment]
The more I think about this, the more I feel like reordering arrays in the back of users is dangerous. Ok for permissions array items order doesn't have meaning, but in most cases it actually does.

That would mean special-casing permissions, which sounds a little overkill. Maybe order should be guaranteed on the server side anyway. Thoughts?

**Comment by glasserc** [comment]
Semantically, `permissions` isn't really a list, it's more like a `set` -- order isn't important and no principal should appear in it twice. I think whenever we know that something is a `set`, we should order it for ease of diffing. In other words, I don't think we should "special case" permissions, we should "general case" all sets. Unfortunately, jsonschema doesn't offer any kind of `set` type -- the closest I think it gets is `type: array` with `uniqueItems` -- so users can't let us do this operation on their data, which makes it kind of a moot point. 😩

Given that, I'd be in favor of slapping in a special case here. I don't think we should implement this on the server side, since it would add overhead to use cases that don't need it -- I don't think diffing permissions is nearly as common as just checking "am I in this list?"

**Comment by n1k0** [comment]
See #413.

**Comment by n1k0** [comment]
Released in [v1.12.0](https://github.com/Kinto/kinto-admin/releases/tag/v1.12.0).
