### ISSUE TITLE
Problems installing kinto-admin

### ISSUE THREAD

**Issue by Grahack** [Kinto/kinto-admin#446]
Hi,  
I encountered several problems using the first described process:

* complaints about not finding `babel-polyfill`, after adding it to `package.json` it was OK,
* `ReferenceError: regeneratorRuntime is not defined` at line 24

     21 |  * @return {Promise}
     22 |  */
     23 | var pMap = exports.pMap = function () {
     24 |   var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee2(list, fn) {
     25 |     var results;
     26 |     return regeneratorRuntime.wrap(function _callee2$(_context2) {
     27 |       while (1) {

I had no problem with the second described process: `git clone…`.

Thanks for kinto!

**Comment by glasserc** [comment]
Hi, sorry for not writing back sooner! What you describe sounds like a missing babel-generator-runtime. We've had some questions in our minds about how to best package kinto libraries (see Kinto/kinto.js#649 and Kinto/kinto.js#650), but I think kinto-admin (as an executable) should be ready to run "out-of-the-box", which means including babel-polyfill as a dependency rather than just as a devDependency. I've opened #456 to try to address this. However, I'm not sure why you continued to encounter the issue even after adding babel-polyfill. Could you elaborate on where you added it -- your own package.json, or somehow to the kinto-admin one?

**Comment by leplatrem** [comment]
Should fixed on master. Feel free to reopen if problems still occur
