### ISSUE TITLE
Users who are part of "review" and "signoff" groups do not get shown the "request review" or "grant review" buttons

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto-admin#495]
I think #471 might have broken something with the conditions under which the "request review" or "grant review" buttons are even shown. The principals for the editors/reviewers are correctly shown in the homepage, and the collection metadata can be edited, but the buttons are mysteriously absent.

**Comment by magopian** [comment]
This was filed following investigations in https://bugzilla.mozilla.org/show_bug.cgi?id=1448157 (comments in there might prove useful to reproduce the issue).

@glasserc @leplatrem do you have any other hints to reproduce the issue locally?

**Comment by magopian** [comment]
So, for starters, this piece of code was "faulty": https://github.com/Kinto/kinto-admin/blob/f56e5982c3a7bf064a021af25143532eb8fe9389/src/plugins/signoff/components.js#L28-L41

What this did was default to saying that a user was a member of a group in any case. It was nearly equivalent with `const isMember = () => true;`.

The reasoning was:
1/ a user can be a member of a group, but not have the permission to read the list of user of this group, so always assume that the user is a member of the group
2/ in any case, if we wrongly assumed that the user was a member of the group, the permissions will be checked later, and the user will not have "unauthorized permissions"

But this means that maybe the current issue was already present before the PR #471, but was simply shadowed (fixed?) by the previous implementation. We might have to investigate a bit deeper.

**Comment by leplatrem** [comment]
Hmm interesting!

There might be a way to reproduce locally, because we could reproduce on stage super easily.

What bothers me though is that the addons/plugins team could review/signoff their blocklist. So either the bug is related some verify specific group setup ([something here](https://github.com/mozilla-services/cloudops-deployment/blob/5c1c5bd0d7ee76f852ea8c8a367437a0a7c5409f/projects/kinto/puppet/yaml/permissions/kinto.prod.yaml#L1177-L1191) that makes the certificates editors/reviewers setup different than others) or the addons/plugins team did everything via the CLI (which I doubt).

Also, I could not reproduce with the basic setup:

![screenshot from 2018-03-27 07-15-37](https://user-images.githubusercontent.com/546692/37973178-c7eed93e-318e-11e8-88d8-f978646f0c16.png)
![screenshot from 2018-03-27 07-14-46](https://user-images.githubusercontent.com/546692/37973180-c8177f2e-318e-11e8-9d0b-9275216b8e5d.png)

Just FYI what I did to get a server running:

- Run kinto-dist
```
$ cd kinto-dist/
$ make serve
```
(in case you never did, you must create a [postgresql database like this](https://github.com/mozilla-services/kinto-dist/blob/ea4b61c83ff366a5ddc3bca0ff2839f2c820f0d7/.travis.yml#L20-L26))

- Run Autograph
```
$ cd kinto-dist/
$ .venv/bin/autograph -c .autograph.yml
```

- Initalize the server with users/data/groups etc.
```
$ cd kinto-dist/
$ bash tests/smoke-tests.sh
```

- Login in Kinto-Admin with 2 different sessions/tab containers as `editor:pass` and `reviewer:pass` 
- Editor makes the changes and requests review
- Reviewer approves them




What you can do to

**Comment by leplatrem** [comment]
I was wrong, they can't https://bugzilla.mozilla.org/show_bug.cgi?id=1445031#c2

**Comment by leplatrem** [comment]
I think this is wrong:

https://github.com/Kinto/kinto-admin/blob/643570c41a017b0a67d263681cd184e77513392e/src/plugins/signoff/components.js#L27

The group information is not in the `source` attribute.

**Comment by magopian** [comment]
This is exactly the piece of code I was looking at, and was trying to reproduce locally (but it took me some time to setup a local server with the signer plugin configured, which was possible thanks to the awesome docs! Mad props! 💯
